#!/usr/bin/env python3
"""Write one PhyloGAS config per state from config.template.yaml.

Every per-state value -- paths, sequence geography, the painted window's start
tick and date, the training window -- is derived from `population.state` and
`population.state_name`, so a state's config differs from the template only in
those two lines plus the run-wide settings below. Generating them, rather than
copying and hand-editing, keeps the five configs from drifting apart (a merged
config once silently reverted to Virginia).

    python scripts/make_state_configs.py --ncov-dir /path/to/ncov
    python scripts/make_state_configs.py --states ma va --num-ticks 250 --training-days 365

Edits are line-level substitutions, so the template's comments survive.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

STATES = {
    "ga": "Georgia",
    "ma": "Massachusetts",
    "mn": "Minnesota",
    "va": "Virginia",
    "wa": "Washington",
}


def sub_once(text: str, pattern: str, repl: str) -> str:
    new, n = re.subn(pattern, repl, text, count=1, flags=re.M)
    if n != 1:
        raise SystemExit(f"template changed: pattern not found: {pattern!r}")
    return new


def render(template: str, st: str, name: str, args) -> str:
    t = template
    t = sub_once(t, r'^(  state: )"[a-z]+"', rf'\g<1>"{st}"')
    t = sub_once(t, r'^(  state_name: )"[^"]*"', rf'\g<1>"{name}"')
    t = sub_once(t, r'^(  num_ticks: )\d+', rf'\g<1>{args.num_ticks}')
    t = sub_once(t, r'^(  days: )\d+', rf'\g<1>{args.training_days}')
    if args.ncov_dir:
        t = sub_once(t, r'^(nextstrain:\n  enabled: )false', r'\g<1>true')
        t = sub_once(t, r'^(  dir: )""', rf'\g<1>"{args.ncov_dir}"')
    # Each state stages its ncov inputs separately: recipe ids (4S__surs) are
    # the same in every state, so a shared folder would let concurrent runs
    # overwrite each other's inputs.
    t = sub_once(t, r'^(  stage_subdir: )"data/phylogas"',
                 r'\g<1>"data/phylogas/{project_name}"')
    if args.max_records:
        t = sub_once(t, r'^    #   max_records: 200000',
                     f'    max_records: {args.max_records}')
    header = (f"# Generated by scripts/make_state_configs.py for {name} ({st}).\n"
              f"# Regenerate rather than edit; change the template or the script.\n")
    return header + t


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--template", default="config.template.yaml")
    ap.add_argument("--outdir", default="configs")
    ap.add_argument("--states", nargs="+", default=list(STATES), choices=list(STATES))
    ap.add_argument("--num-ticks", type=int, default=300,
                    help="Days painted from each state's first importation "
                         "(default: 300, as the original Virginia run).")
    ap.add_argument("--training-days", type=int, default=400,
                    help="Training-window length from the same start (default: 400).")
    ap.add_argument("--ncov-dir", default=None,
                    help="ncov checkout; given, Nextstrain is enabled.")
    ap.add_argument("--max-records", type=int, default=200000,
                    help="Cap for the clock benchmark's mu_truth (0 = no cap).")
    args = ap.parse_args()

    template = Path(args.template).read_text()
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    for st in args.states:
        path = out / f"{st}.yaml"
        path.write_text(render(template, st, STATES[st], args))
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
